name: kcsite1
favicon: null
layout_spectrum: 0.26069463905878365
typography_spectrum: 0.25535500468686223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8623185765463859
  lightness: 0.42376587400212884
  saturation: 0.48275408800691366
  rhythmicContrast: 0.9604235820006579
purpose: []
